#!/bin/bash
# Script to add Phantom of the Chakras files to Xcode project

echo "Adding Phantom of the Chakras files to Xcode project..."
echo ""
echo "Please follow these steps in Xcode:"
echo ""
echo "1. Open VybeMVP.xcodeproj in Xcode"
echo ""
echo "2. Right-click on the 'Features' folder in the project navigator"
echo ""
echo "3. Select 'Add Files to \"VybeMVP\"...'"
echo ""
echo "4. Navigate to Features/Chakras and select the entire folder"
echo ""
echo "5. Make sure these options are checked:"
echo "   - Copy items if needed: UNCHECKED (files are already in place)"
echo "   - Create groups: CHECKED"
echo "   - Add to targets: VybeMVP (CHECKED)"
echo ""
echo "6. Click 'Add'"
echo ""
echo "The following files should be added:"
echo "  - Features/Chakras/ChakraModel.swift"
echo "  - Features/Chakras/ChakraManager.swift"
echo "  - Features/Chakras/ChakraSymbolView.swift"
echo "  - Features/Chakras/PhantomChakrasView.swift"
echo ""
echo "After adding the files, build and run the project to see the new Chakras tab!" 